spring:
  application:
    name: aluno-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:alunodb

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true